/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include <open62541/server.h>
#include <open62541/types.h>

#include "test_helpers.h"

#include <stdlib.h>
#include <check.h>

/* A const custom DataType array as generated by generate_datatypes.py with
 * --namespaceMap "2:http://open62541.org/customtypes/". The namespace index 2
 * is baked into the NodeIds. */

typedef struct {
    UA_Float x;
    UA_Float y;
    UA_Float z;
} Point;

#define Point_padding_y offsetof(Point,y) - offsetof(Point,x) - sizeof(UA_Float)
#define Point_padding_z offsetof(Point,z) - offsetof(Point,y) - sizeof(UA_Float)

static const UA_DataTypeMember Point_members[3] = {
    {
        UA_TYPENAME("x")           /* .memberName */
        &UA_TYPES[UA_TYPES_FLOAT], /* .memberType */
        0,                         /* .padding */
        false,                     /* .isArray */
        false                      /* .isOptional */
    },
    {
        UA_TYPENAME("y")
        &UA_TYPES[UA_TYPES_FLOAT],
        Point_padding_y,
        false,
        false
    },
    {
        UA_TYPENAME("z")
        &UA_TYPES[UA_TYPES_FLOAT],
        Point_padding_z,
        false,
        false
    }
};

static const UA_DataType customTypes[1] = {{
    UA_TYPENAME("Point")              /* .typeName */
    {2, UA_NODEIDTYPE_NUMERIC, {4242}}, /* .typeId */
    {2, UA_NODEIDTYPE_NUMERIC, {4243}}, /* .binaryEncodingId */
    {2, UA_NODEIDTYPE_NUMERIC, {4244}}, /* .xmlEncodingId */
    sizeof(Point),                    /* .memSize */
    UA_DATATYPEKIND_STRUCTURE,        /* .typeKind */
    true,                             /* .pointerFree */
    false,                            /* .overlayable */
    3,                                /* .membersSize */
    Point_members
}};

/* The namespace URIs behind the baked namespace indices. Index 1 (the
 * application namespace) is unused by the types and stays empty. */
static const UA_String customTypesNamespaces[3] = {
    UA_STRING_STATIC("http://opcfoundation.org/UA/"),
    {0, NULL},
    UA_STRING_STATIC("http://open62541.org/customtypes/")
};

static UA_Server *server = NULL;

static void setup(void) {
    server = UA_Server_newForUnitTest();
    ck_assert(server != NULL);
}

static void teardown(void) {
    UA_Server_delete(server);
}

/* The custom namespace is registered at index 2, matching the baked indices.
 * The const array must be linked without a copy. */
START_TEST(addDataTypeArray_zeroCopy) {
    UA_StatusCode retval =
        UA_Server_addDataTypeArray(server, 1, customTypes,
                                   customTypesNamespaces, 3);
    ck_assert_uint_eq(retval, UA_STATUSCODE_GOOD);

    /* The namespace was added at the baked index */
    size_t nsIndex = 0;
    retval = UA_Server_getNamespaceByName(
        server, UA_STRING("http://open62541.org/customtypes/"), &nsIndex);
    ck_assert_uint_eq(retval, UA_STATUSCODE_GOOD);
    ck_assert_uint_eq(nsIndex, 2);

    /* The lookup returns the const array entry itself */
    UA_NodeId typeId = UA_NODEID_NUMERIC(2, 4242);
    const UA_DataType *found = UA_Server_findDataType(server, &typeId);
    ck_assert_ptr_eq((const void*)found, (const void*)&customTypes[0]);
} END_TEST

/* A filler namespace shifts the custom namespace to index 3. A copy of the
 * type array with rewritten namespace indices must be registered. The const
 * input array stays untouched and the members remain shared. */
START_TEST(addDataTypeArray_copyOnMismatch) {
    UA_UInt16 fillerIndex =
        UA_Server_addNamespace(server, "http://open62541.org/filler/");
    ck_assert_uint_eq(fillerIndex, 2);

    UA_StatusCode retval =
        UA_Server_addDataTypeArray(server, 1, customTypes,
                                   customTypesNamespaces, 3);
    ck_assert_uint_eq(retval, UA_STATUSCODE_GOOD);

    /* The registered type carries the runtime namespace index 3 */
    UA_NodeId typeId = UA_NODEID_NUMERIC(3, 4242);
    const UA_DataType *found = UA_Server_findDataType(server, &typeId);
    ck_assert(found != NULL);
    ck_assert_ptr_ne((const void*)found, (const void*)&customTypes[0]);
    ck_assert_uint_eq(found->binaryEncodingId.namespaceIndex, 3);
    ck_assert_uint_eq(found->binaryEncodingId.identifier.numeric, 4243);
    ck_assert_uint_eq(found->xmlEncodingId.namespaceIndex, 3);

    /* The members are shared with the const input array */
    ck_assert_ptr_eq((const void*)found->members,
                     (const void*)Point_members);

    /* The const input array is untouched */
    ck_assert_uint_eq(customTypes[0].typeId.namespaceIndex, 2);

    /* No entry under the baked namespace index */
    UA_NodeId bakedId = UA_NODEID_NUMERIC(2, 4242);
    ck_assert(UA_Server_findDataType(server, &bakedId) == NULL);
} END_TEST

/* Registering the same array twice must not create a duplicate entry */
START_TEST(addDataTypeArray_idempotent) {
    UA_StatusCode retval =
        UA_Server_addDataTypeArray(server, 1, customTypes,
                                   customTypesNamespaces, 3);
    ck_assert_uint_eq(retval, UA_STATUSCODE_GOOD);
    retval = UA_Server_addDataTypeArray(server, 1, customTypes,
                                        customTypesNamespaces, 3);
    ck_assert_uint_eq(retval, UA_STATUSCODE_GOOD);

    size_t entries = 0;
    for(const UA_DataTypeArray *ar = UA_Server_getConfig(server)->customDataTypes;
        ar; ar = ar->next)
        entries++;
    ck_assert_uint_eq(entries, 1);
} END_TEST

static Suite *testSuite_customDataTypeArray(void) {
    Suite *s = suite_create("Custom DataType Array");
    TCase *tc = tcase_create("UA_Server_addDataTypeArray");
    tcase_add_checked_fixture(tc, setup, teardown);
    tcase_add_test(tc, addDataTypeArray_zeroCopy);
    tcase_add_test(tc, addDataTypeArray_copyOnMismatch);
    tcase_add_test(tc, addDataTypeArray_idempotent);
    suite_add_tcase(s, tc);
    return s;
}

int main(void) {
    Suite *s = testSuite_customDataTypeArray();
    SRunner *sr = srunner_create(s);
    srunner_set_fork_status(sr, CK_NOFORK);
    srunner_run_all(sr, CK_NORMAL);
    int number_failed = srunner_ntests_failed(sr);
    srunner_free(sr);
    return (number_failed == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
}
